name: medical_app
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Localization
  easy_localization: ^3.0.7+1
  intl: ^0.20.2

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^8.0.3

  # API & Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0

  # Code Generation / Data Classes
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Splash Screen
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: any
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true

  # Uncomment and add your assets when ready
  # assets:
  #   - assets/images/
  #   - assets/translations/

  # Uncomment and add your fonts when ready
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
