// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfsjxOYZqCW4HNgyPCYk7XZkWJxfvQdxo',
    appId: '1:29098399785:web:1c09edfc43dd36c4ad6438',
    messagingSenderId: '29098399785',
    projectId: 'flutter-app-distribution-379c9',
    authDomain: 'flutter-app-distribution-379c9.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-379c9.firebasestorage.app',
    measurementId: 'G-BKVSX8NRR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ggKV9svXqBnDxgWfPKEaQfUhuL3CT4g',
    appId: '1:29098399785:android:ca4073c9fa734cb9ad6438',
    messagingSenderId: '29098399785',
    projectId: 'flutter-app-distribution-379c9',
    storageBucket: 'flutter-app-distribution-379c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvwwsVeHjZLw_mmyxRw9EeH5o-VI6ZgM',
    appId: '1:29098399785:ios:0cbabe54f81d8719ad6438',
    messagingSenderId: '29098399785',
    projectId: 'flutter-app-distribution-379c9',
    storageBucket: 'flutter-app-distribution-379c9.firebasestorage.app',
    iosBundleId: 'com.example.medicalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvwwsVeHjZLw_mmyxRw9EeH5o-VI6ZgM',
    appId: '1:29098399785:ios:0cbabe54f81d8719ad6438',
    messagingSenderId: '29098399785',
    projectId: 'flutter-app-distribution-379c9',
    storageBucket: 'flutter-app-distribution-379c9.firebasestorage.app',
    iosBundleId: 'com.example.medicalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfsjxOYZqCW4HNgyPCYk7XZkWJxfvQdxo',
    appId: '1:29098399785:web:cc0c5f8fbfdd0517ad6438',
    messagingSenderId: '29098399785',
    projectId: 'flutter-app-distribution-379c9',
    authDomain: 'flutter-app-distribution-379c9.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-379c9.firebasestorage.app',
    measurementId: 'G-4C53PGCY7F',
  );
}
